CVO/Models/Album.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace CVO.Models
{
    public class Album
    {

        public int Id { get; set; }

        [Required(ErrorMessage = "Titel is verplicht!")]
        [DataType(DataType.Text)]
        [DisplayName("Naam")]
        public string Title { get; set; }

        [DisplayName("Actief")]
        public bool Active { get; set; }

        [Required(ErrorMessage = "Foto is verplicht!")]
        [DataType(DataType.Upload)]
        [DisplayName("Foto")]
        public string Image { get; set; }

        [Required(ErrorMessage = "Link is verplicht!")]
        [DataType(DataType.Text)]
        [DisplayName("Link")]
        public string Url { get; set; }

        [DisplayName("Datum")]
        [DataType(DataType.DateTime)]
        public DateTime DateCreated { get; set; }

        public HtmlString addLinkToImage(string website, string image, string name)
        {
            //Check if website not is null
            //Null = show image
            //Not Null = a href to website + img-hover class
            //Type = HtmlString
            HtmlString htmlstring;

            if (website == null)
            {
                htmlstring = new HtmlString("<img src='" + image + "' alt='" + name + "' class='img-responsive img-album img-center' />");
            }
            else
            {
                htmlstring = new HtmlString("<a href='" + website + "' target='_blank'><img src='" + image + "' alt='" + name + "' class='img-responsive img-hover img-album img-center'/></a>");
            }

            return htmlstring;
        }
    }
}

CVO/Models/Kalender.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CVO.Models
{
    public class Kalender
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Titel is verplicht!")]
        [DisplayName("Titel")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Startdatum is verplicht")]
        [DataType(DataType.DateTime)]
        [DisplayName("Startdatum")]
        public DateTime DateStart { get; set; }

        [Required(ErrorMessage = "Einddatum is verplicht")]
        [DataType(DataType.DateTime)]
        [DisplayName("Einddatum")]
        public DateTime DateEnd { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("Omschrijving")]
        public string Description { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("Locatie")]
        public string Location { get; set; }

        [DisplayName("Actief")]
        public bool Active { get; set; }

        [DataType(DataType.Upload)]
        [DisplayName("Foto")]
        public string Image { get; set; }

        [DisplayName("Datum toegevoegd")]
        [DataType(DataType.DateTime)]
        public DateTime DateCreated { get; set; }

        public string ShowIndexFormat(DateTime dateStart, DateTime dateEnd)
        {
            string format;
            if (dateStart == dateEnd)
            {
                format = dateStart.Day.ToString();
                format += " " + Date.ReturnDutchNameOfMonth(dateStart);
            }
            else
            {
                format = dateStart.Day.ToString();
                format += " " + Date.ReturnDutchNameOfMonth(dateStart);
                format += " - ";
                format += dateEnd.Day.ToString();
                format += " " + Date.ReturnDutchNameOfMonth(dateEnd);
            }

            return format;
        }

        public string GetInputDateValue(DateTime item)
        {
            //Change a DateTime to input type = date format (yyyy-MM-dd)
            string monthFormat;
            string dayFormat;

            //Make sure month has 2 characters
            if (item.Month < 10)
            {
                monthFormat = "0" + item.Month;
            }
            else
            {
                monthFormat = item.Month.ToString();
            }

            //Make sure day has 2 characters
            if (item.Day < 10)
            {
                dayFormat = "0" + item.Day;
            }
            else
            {
                dayFormat = item.Day.ToString();
            }
            string date = item.Year + "-" + monthFormat + "-" + dayFormat;

            return date;
        }


    }
}

CVO/Models/Nieuws.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CVO.Models
{
    public class Nieuws
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Titel is verplicht!")]
        [DisplayName("Titel")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Content is verplicht!")]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }

        [DisplayName("Actief")]
        public bool Active { get; set; }

        [DisplayName("Vastgezet")]
        public bool Locked { get; set; }

        [DataType(DataType.Upload)]
        [DisplayName("Foto")]
        public string Image { get; set; }

        [DisplayName("Datum")]
        [DataType(DataType.DateTime)]
        public DateTime DateCreated { get; set; }
    }
}

CVO/Models/Team.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CVO.Models
{
    public class Team
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Naam is verplicht!")]
        [DisplayName("Team")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Foto is verplicht")]
        [DataType(DataType.Upload)]
        [DisplayName("Foto")]
        public string Image { get; set; }

        [DisplayName("Omschrijving")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DisplayName("Actief")]
        public bool Active { get; set; }

        [DisplayName("Sponsor naam")]
        public string SponsorName { get; set; }

        [DisplayName("Sponsor website")]
        public string SponsorWebsite { get; set; }

        [DisplayName("Sponsor foto")]
        [DataType(DataType.Upload)]
        public string SponsorImage { get; set; }

        [DisplayName("Datum")]
        [DataType(DataType.DateTime)]
        public DateTime DateCreated { get; set; }
    }
}

CVO/Controllers/NieuwsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using CVO.DAL;
using CVO.Models;
using CVO.ViewModels;

namespace CVO.Controllers
{
    public class NieuwsController : Controller
    {
        private CvoDbContext db = new CvoDbContext();
        private bool isLoggedIn;
        private bool hasPermission;
        private string redirectActionForLogin;
        private string redirectControllerForLogin;
        private string redirectActionForPermission;
        private string redirectControllerForPermission;
        private AdminVM adminVM;

        public NieuwsController()
        {
            isLoggedIn = false;
            hasPermission = false;

            redirectActionForLogin = "Login";
            redirectControllerForLogin = "Admin";

            redirectActionForPermission = "Index";
            redirectControllerForPermission = "Admin";

            //Check if user is logged in
            if (Gebruiker.CheckIfLoggedIn())
            {
                isLoggedIn = true;

                //Get level of page from database
                var newsLevel = db.Levels.Find(7).MinLevel;

                //Check if page level not is higher than user level
                if (newsLevel <= Gebruiker.ReturnCurrentUser().Level)
                {
                    hasPermission = true;
                }

                adminVM = new AdminVM();
            }
        }

        // GET: Nieuws
        public ActionResult Index()
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            else if (!hasPermission)
            {
                return RedirectToAction(redirectActionForPermission, redirectControllerForPermission, null);
            }

            var nieuws = from k in db.Nieuws
                         orderby k.DateCreated descending
                         select k;

            adminVM.NieuwsList = nieuws.ToList();

            return View(adminVM);
        }

        // GET: Nieuws/Details/5
        public ActionResult Details(int? id)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            else if (!hasPermission)
            {
                return RedirectToAction(redirectActionForPermission, redirectControllerForPermission, null);
            }

            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Nieuws nieuws = db.Nieuws.Find(id);
            if (nieuws == null)
            {
                return RedirectToAction("Index");
            }

            adminVM.Nieuws = nieuws;

            return View(adminVM);
        }

        // GET: Nieuws/Create
        public ActionResult Create()
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            else if (!hasPermission)
            {
                return RedirectToAction(redirectActionForPermission, redirectControllerForPermission, null);
            }

            //Create object of Nieuws
            Nieuws nieuws = new Nieuws();

            //Set active to true, so active checkbox is checked by default
            nieuws.Active = true;

            //Set DateCreated to DateTime.Now
            nieuws.DateCreated = DateTime.Now;

            adminVM.Nieuws = nieuws;

            return View(adminVM);
        }

        // POST: Nieuws/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Content,Active,Locked,Image,DateCreated")] Nieuws nieuws)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            else if (!hasPermission)
            {
                return RedirectToAction(redirectActionForPermission, redirectControllerForPermission, null);
            }

            if (nieuws.Image != null)
            {
                //Save image to server and change name to imagepath
                nieuws.Image = Image.SaveImageToServer();
            }

            if (ModelState.IsValid)
            {
                db.Nieuws.Add(nieuws);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            adminVM.Nieuws = nieuws;

            return View(adminVM);
        }

        // GET: Nieuws/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            else if (!hasPermission)
            {
                return RedirectToAction(redirectActionForPermission, redirectControllerForPermission, null);
            }

            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Nieuws nieuws = db.Nieuws.Find(id);
            if (nieuws == null)
            {
                return RedirectToAction("Index");
            }

            adminVM.Nieuws = nieuws;

            return View(adminVM);
        }

        // POST: Nieuws/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Content,Active,Locked,Image,DateCreated")] Nieuws nieuws)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            else if (!hasPermission)
            {
                return RedirectToAction(redirectActionForPermission, redirectControllerForPermission, null);
            }

            if (ModelState.IsValid)
            {
                db.Entry(nieuws).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            adminVM.Nieuws = nieuws;

            return View(adminVM);
        }

        // GET: Nieuws/EditImage/5
        public ActionResult EditImage(int? id)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            else if (!hasPermission)
            {
                return RedirectToAction(redirectActionForPermission, redirectControllerForPermission, null);
            }

            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Nieuws nieuws = db.Nieuws.Find(id);
            if (nieuws == null)
            {
                return RedirectToAction("Index");
            }

            adminVM.Nieuws = nieuws;

            return View(adminVM);
        }

        // POST: Nieuws/EditImage/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditImage([Bind(Include = "Id,Title,Content,Active,Locked,Image,DateCreated")] Nieuws nieuws)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            else if (!hasPermission)
            {
                return RedirectToAction(redirectActionForPermission, redirectControllerForPermission, null);
            }

            if (nieuws.Image != null)
            {
                //Save image to server and change name to imagepath
                nieuws.Image = Image.SaveImageToServer();
            }
            else
            {
                return RedirectToAction("Edit", new { id = nieuws.Id });
            }

            if (ModelState.IsValid)
            {
                db.Entry(nieuws).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit", new { id = nieuws.Id });
            }
            return RedirectToAction("Edit", new { id = nieuws.Id });
        }

        // POST: Nieuws/DeleteImage/5
        [HttpPost, ActionName("DeleteImage")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteImage([Bind(Include = "Id,Title,Content,Active,Locked,Image,DateCreated")] Nieuws nieuws)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            else if (!hasPermission)
            {
                return RedirectToAction(redirectActionForPermission, redirectControllerForPermission, null);
            }

            if (nieuws.Image != null)
            {
                //Delete image
                Image.DeleteImageFromServer(nieuws.Image);

                //Set image to null in database
                nieuws.Image = null;
            }

            if (ModelState.IsValid)
            {
                db.Entry(nieuws).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            adminVM.Nieuws = nieuws;

            return View(adminVM);
        }

        // GET: Nieuws/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            else if (!hasPermission)
            {
                return RedirectToAction(redirectActionForPermission, redirectControllerForPermission, null);
            }

            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Nieuws nieuws = db.Nieuws.Find(id);
            if (nieuws == null)
            {
                return RedirectToAction("Index");
            }

CVO/Views/Home/SearchDirectives/Albums.cshtml
@model CVO.ViewModels.IndexVM
@using PagedList.Mvc
@using CVO.Models

@if (Model.AlbumPagedList.Count != 0)
{
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading"><h3>Albums</h3></div>
            <div class="panel-body">
                @foreach (var album in Model.AlbumPagedList)
                {
                    <p>
                        <b>@album.Title</b><br />
                        <a href="@album.Url" target="_blank">@album.Url</a>
                        <span class="small-date float-right">
                            @Date.ReturnDutchNameOfMonth(album.DateCreated) @album.DateCreated.Day, @album.DateCreated.Year
                        </span>
                    </p>
                            <hr />
                }
                <p class="text-center">Pagina @(Model.AlbumPagedList.PageCount < Model.AlbumPagedList.PageNumber ? 0 : Model.AlbumPagedList.PageNumber) van @Model.AlbumPagedList.PageCount</p>
                <p>@Html.PagedListPager(Model.AlbumPagedList, page => Url.Action("Zoeken", new { search = Model.Search, pageAlbum = page }))</p>
            </div>
        </div>
    </div>
}

CVO/Views/Home/SearchDirectives/Kalender.cshtml
@model CVO.ViewModels.IndexVM
@using CVO.Models
@using PagedList.Mvc

@if (Model.KalenderPagedList.Count != 0)
{
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading"><h3>Kalender</h3></div>
            <div class="panel-body">
                @foreach (var calendar in Model.KalenderPagedList)
                {
                    <p>
                        <b>@Html.ActionLink(calendar.Title, "KalenderItem", new { id = calendar.Id })</b><br />
                        @Text.GetPartOfString(calendar.Description, 100)
                        <span class="small-date float-right">
                            @Date.ReturnDutchNameOfMonth(calendar.DateCreated) @calendar.DateCreated.Day, @calendar.DateCreated.Year
                        </span>
                    </p>
                            <hr />
                }
                <p class="text-center">Pagina @(Model.KalenderPagedList.PageCount < Model.KalenderPagedList.PageNumber ? 0 : Model.KalenderPagedList.PageNumber) van @Model.KalenderPagedList.PageCount</p>
                <p>@Html.PagedListPager(Model.KalenderPagedList, page => Url.Action("Zoeken", new { search = Model.Search, pageKalender = page }))</p>
            </div>
        </div>
    </div>
}

CVO/Views/Home/SearchDirectives/Nieuws.cshtml
@model CVO.ViewModels.IndexVM
@using CVO.Models
@using PagedList.Mvc

@if (Model.NieuwsPagedList.Count != 0)
{
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading"><h3>Nieuws</h3></div>
            <div class="panel-body">
                @foreach (var news in Model.NieuwsPagedList)
                {
                    <p>
                        <b>@Html.ActionLink(news.Title, "Nieuws", new { id = news.Id })</b><br />
                        @Text.GetPartOfString(news.Content, 100)
                        <span class="small-date float-right">
                            @Date.ReturnDutchNameOfMonth(news.DateCreated) @news.DateCreated.Day, @news.DateCreated.Year
                            @if (news.Locked == true)
                            {
                                <i class="fa fa-lock"></i>
                            }
                        </span>
                    </p>
                            <hr />
                }
                <p class="text-center">Pagina @(Model.NieuwsPagedList.PageCount < Model.NieuwsPagedList.PageNumber ? 0 : Model.NieuwsPagedList.PageNumber) van @Model.NieuwsPagedList.PageCount</p>
                <p>@Html.PagedListPager(Model.NieuwsPagedList, page => Url.Action("Zoeken", new { search = Model.Search, pageNieuws = page }))</p>
            </div>
        </div>
    </div>
}

CVO/Views/Home/SearchDirectives/Teams.cshtml
@model CVO.ViewModels.IndexVM
@using PagedList.Mvc
@using CVO.Models

@if (Model.TeamPagedList.Count != 0)
{
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading"><h3>Teams</h3></div>
            <div class="panel-body">
                @foreach (var team in Model.TeamPagedList)
                {
                    <p>
                        <b>@Html.ActionLink(team.Name, "Team", new { id = team.Id })</b><br />
                        @Text.GetPartOfString(team.Description, 100)
                        <span class="small-date float-right">
                            @Date.ReturnDutchNameOfMonth(team.DateCreated) @team.DateCreated.Day, @team.DateCreated.Year
                        </span>
                    </p>
                    <hr />
                }
                <p class="text-center">Pagina @(Model.TeamPagedList.PageCount < Model.TeamPagedList.PageNumber ? 0 : Model.TeamPagedList.PageNumber) van @Model.TeamPagedList.PageCount</p>
                <p>@Html.PagedListPager(Model.TeamPagedList, page => Url.Action("Zoeken", new { search = Model.Search, pageTeam = page }))</p>
            </div>
        </div>
    </div>
}