CVO/Models/ChangePassword.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;

namespace CVO.Models
{
    public class ChangePassword
    {
        [Required]
        public int Id { get; set; }

        [Required(ErrorMessage = "Huidig wachtwoord is vereist")]
        [DataType(DataType.Password)]
        [DisplayName("Huidig wachtwoord")]
        public string CurrentPassword { get; set; }

        [Required(ErrorMessage = "Nieuw wachtwoord is vereist")]
        [DataType(DataType.Password)]
        [DisplayName("Nieuw wachtwoord")]
        public string NewPassword { get; set; }

        [Required(ErrorMessage = "Nieuw wachtwoord herhaling is vereist")]
        [DataType(DataType.Password)]
        [DisplayName("Nieuw wachtwoord herhaling")]
        public string NewPasswordRepeat { get; set; }

        public string ChechIfPasswordMeetsRequirements(ChangePassword changePassword, Gebruiker gebruiker)
        {

            //Call gebruiker method to encrypt passwords
            string encryptedCurrentPassword = Gebruiker.EncryptPassword(changePassword.CurrentPassword);
            string encryptedNewPassword = Gebruiker.EncryptPassword(changePassword.NewPassword);
            string encryptedNewPasswordRepeat = Gebruiker.EncryptPassword(changePassword.NewPasswordRepeat);

            //Check if password is the same as database password
            if (encryptedCurrentPassword != gebruiker.Password)
            {
                return "Huidig wachtwoord is onjuist";
            }

            //Regex for special regex
            var specialCharactersRegex = new Regex("^[!,@,#,$,%,^,&,*,?,_,~,-,(,)]*$");

            //Check if new password contains at least 8 characters
            if (changePassword.NewPassword.Length < 8)
            {
                return "Wachtwoord moet minstens 8 karakters bevatten";
            }
            //Check if new password contains a number
            else if (!changePassword.NewPassword.Any(char.IsDigit))
            {
                return "Wachtwoord moet minstens 1 cijfer bevatten";
            }
            //Check if new password contains a capital letter
            else if (!changePassword.NewPassword.Any(char.IsUpper))
            {
                return "Wachtwoord moet minstens 1 hoofdletter bevatten";
            }
            //Check if new password contains a special character
            else if (specialCharactersRegex.IsMatch(changePassword.NewPassword))
            {
                return "Wachtwoord moet minstens 1 speciaal karakter bevatten";
            }

            //Check if newPassword and newPasswordRepeat are the same
            if (encryptedNewPassword != encryptedNewPasswordRepeat)
            {
                return "Wachtwoorden zijn niet hetzelfde";
            }

            return null;
        }
    }
}

CVO/Controllers/ProfielController.cs
using CVO.DAL;
using CVO.Models;
using CVO.ViewModels;
using System;
using System.Data.Entity;
using System.Web.Mvc;

namespace CVO.Controllers
{
    public class ProfielController : Controller
    {
        private CvoDbContext db = new CvoDbContext();
        private bool isLoggedIn;
        private string redirectActionForLogin;
        private string redirectControllerForLogin;
        private AdminVM adminVM;

        public ProfielController()
        {
            isLoggedIn = false;

            redirectActionForLogin = "Login";
            redirectControllerForLogin = "Admin";

            //Check if user is logged in
            if (Gebruiker.CheckIfLoggedIn())
            {
                isLoggedIn = true;

                adminVM = new AdminVM();
            }
        }

        // GET: Profiel/ChangePassword/5
        public ActionResult ChangePassword(int? id)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }

            if (id == null)
            {
                return RedirectToAction("Index", "Admin", null);
            }

            //If id not is the id of the current user
            //Redirect to Index
            if (id != Gebruiker.ReturnCurrentUser().Id)
            {
                return RedirectToAction("Index", "Admin", null);
            }

            ChangePassword changePassword = new ChangePassword();
            changePassword.Id = (int)id;

            adminVM.ChangePassword = changePassword;

            return View(adminVM);
        }

        // POST: Profiel/ChangePassword/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword([Bind(Include = "Id,CurrentPassword,NewPassword,NewPasswordRepeat")] ChangePassword changePassword)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }

            //RubenTODO: Functionaliteit in model

            //Check if form input is valid
            if (ModelState.IsValid)
            {
                //Get current user from the database
                Gebruiker gebruiker = db.Gebruikers.Find(changePassword.Id);

                var errorMessage = changePassword.ChechIfPasswordMeetsRequirements(changePassword, gebruiker);

                if (errorMessage == null)
                {
                    string encryptedNewPassword = Gebruiker.EncryptPassword(changePassword.NewPassword);

                    //Set password in database to new encrypted password
                    gebruiker.Password = encryptedNewPassword;
                    gebruiker.LastModifiedAt = DateTime.Now;

                    db.Entry(gebruiker).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Edit", new { id = gebruiker.Id });
                }
                else
                {
                    ViewBag.errorMessage = errorMessage;
                    return View(adminVM);
                }
            }
            else
            {
                return View(adminVM);
            }
        }

        // GET: Profiel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }

            if (id == null)
            {
                return RedirectToAction("Index", "Admin", null);
            }

            //If id not is the id of the current user
            //Redirect to Index
            if (id != Gebruiker.ReturnCurrentUser().Id)
            {
                return RedirectToAction("Index", "Admin", null);
            }

            Gebruiker gebruiker = db.Gebruikers.Find(id);

            if (gebruiker == null)
            {
                return RedirectToAction("Index", "Admin", null);
            }

            adminVM.Gebruiker = gebruiker;

            return View(adminVM);
        }

        // POST: Profiel/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email,Image,Password,Level,IsBlocked,LastModifiedAt,CreatedAt,MainAccount")] Gebruiker gebruiker)
        {

            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }

            //If id not is the id of the current user
            //Redirect to Index
            if (gebruiker.Id != Gebruiker.ReturnCurrentUser().Id)
            {
                return RedirectToAction("Index", "Admin", null);
            }

            //RubenTODO: Controleren of email al bestaat in de database

            if (ModelState.IsValid)
            {
                gebruiker.LastModifiedAt = DateTime.Now;
                //Save changes in database
                db.Entry(gebruiker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Admin", null);
            }

            return RedirectToAction("Index", "Admin", null);
        }

        // GET: Gebruiker/EditImage/5
        public ActionResult EditImage(int? id)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            //If id not is the id of the current user
            //Redirect to Index
            if (id != Gebruiker.ReturnCurrentUser().Id)
            {
                return RedirectToAction("Index", "Admin", null);
            }


            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Gebruiker gebruiker = db.Gebruikers.Find(id);
            if (gebruiker == null)
            {
                return RedirectToAction("Index");
            }

            adminVM.Gebruiker = gebruiker;

            return View(adminVM);
        }

        // POST: Gebruiker/EditImage/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditImage([Bind(Include = "Id,FirstName,LastName,Email,Image,Password,Level,IsBlocked,LastModifiedAt,CreatedAt,MainAccount")] Gebruiker gebruiker)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }
            //If id not is the id of the current user
            //Redirect to Index
            if (gebruiker.Id != Gebruiker.ReturnCurrentUser().Id)
            {
                return RedirectToAction("Index", "Admin", null);
            }


            if (gebruiker.Image != null)
            {
                //Save image to server and change name to imagepath
                gebruiker.Image = Image.SaveImageToServer();
            }
            else
            {
                return RedirectToAction("Edit", new { id = gebruiker.Id });
            }
            if (ModelState.IsValid)
            {
                gebruiker.LastModifiedAt = DateTime.Now;
                db.Entry(gebruiker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit", new { id = gebruiker.Id });
            }
            return RedirectToAction("Edit", new { id = gebruiker.Id });
        }

        // POST: Profiel/DeleteImage
        [HttpPost, ActionName("DeleteImage")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteImage([Bind(Include = "Id,FirstName,LastName,Email,Image,Password,Level,IsBlocked,LastModifiedAt,CreatedAt,MainAccount")] Gebruiker gebruiker)
        {
            if (!isLoggedIn)
            {
                return RedirectToAction(redirectActionForLogin, redirectControllerForLogin, null);
            }

            //If id not is the id of the current user
            //Redirect to Index
            if (gebruiker.Id != Gebruiker.ReturnCurrentUser().Id)
            {
                return RedirectToAction("Index", "Admin", null);
            }

            if (gebruiker.Image != null)
            {
                //Delete image
                Image.DeleteImageFromServer(gebruiker.Image);

                //Set image to null in database
                gebruiker.Image = null;
            }

            if (ModelState.IsValid)
            {
                db.Entry(gebruiker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit");
            }

            return RedirectToAction("Edit");
        }
    }
}

CVO/Views/Profiel/ChangePassword.cshtml
@model CVO.ViewModels.AdminVM

@{
    ViewBag.Title = "Wachtwoord wijzigen";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default panel-login">
        <div class="panel-heading"><h3>Registreren</h3></div>
        <div class="panel-body text-center">
            <span class="errorText">@ViewBag.errorMessage</span>
            @if (ViewBag.errorMessage != null)
            {
                <br />
            }

            @using (Html.BeginForm(null, null, FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ChangePassword.Id)

                    @* Current password *@
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>@Html.DisplayNameFor(model => model.ChangePassword.CurrentPassword)</label>
                            @Html.EditorFor(model => model.ChangePassword.CurrentPassword, new { htmlAttributes = new { @class = "form-control", @placeholder = "Wachtwoord" } })
                            @Html.ValidationMessageFor(model => model.ChangePassword.CurrentPassword, "", new { @class = "text-danger" })

                        </div>
                    </div>

                    @* New password *@
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>@Html.DisplayNameFor(model => model.ChangePassword.NewPassword)</label>
                            @Html.EditorFor(model => model.ChangePassword.NewPassword, new { htmlAttributes = new { @class = "form-control", @placeholder = "Wachtwoord" } })
                            @Html.ValidationMessageFor(model => model.ChangePassword.NewPassword, "", new { @class = "text-danger" })

                        </div>
                    </div>

                    @* New password repeat *@
                    <div class="form-group">
                        <div class="col-md-12">
                            <label>@Html.DisplayNameFor(model => model.ChangePassword.NewPasswordRepeat)</label>
                            @Html.EditorFor(model => model.ChangePassword.NewPasswordRepeat, new { htmlAttributes = new { @class = "form-control", @placeholder = "Wachtwoord herhaling" } })
                            @Html.ValidationMessageFor(model => model.ChangePassword.NewPasswordRepeat, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="progress progress-striped active">
                        <div id="passwordStrength" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"></div>
                    </div>

                    <div class="passwordRequirements">
                        <ul>
                            <li id="pwMinCharacters">Minstens 8 karakters </li>
                            <li id="pwCapitalLetter">Minstens 1 hoofdletter</li>
                            <li id="pwNumber">Minstens 1 cijfer</li>
                            <li id="pwAttribute">Minstens 1 speciaal teken</li>
                        </ul>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12 text-center">
                            <button type="submit" class="btn btn-lg btn-success btn-block" id="passwordButton" disabled>Wijzigen</button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

CVO/Views/Profiel/Edit.cshtml
@model CVO.ViewModels.AdminVM
@using CVO.Models

@{
    ViewBag.Title = "Wijzigen";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Wijzigen</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Profiel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Gebruiker.Id)
        @Html.HiddenFor(model => model.Gebruiker.Image)
        @Html.HiddenFor(model => model.Gebruiker.Password)
        @Html.HiddenFor(model => model.Gebruiker.LastModifiedAt)
        @Html.HiddenFor(model => model.Gebruiker.CreatedAt)
        @Html.HiddenFor(model => model.Gebruiker.IsBlocked)
        @Html.HiddenFor(model => model.Gebruiker.MainAccount)
        @Html.HiddenFor(model => model.Gebruiker.Level)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">

                @if (Model.Gebruiker.Image == null)
                {
                    @Html.ActionLink("Profielfoto invoeren", "EditImage", null, new { id = Model.Gebruiker.Id }, htmlAttributes: new { @class = "btn btn-default" })
                }
                else
                {
                    @Html.ActionLink("Profielfoto wijzigen", "EditImage", null, new { id = Model.Gebruiker.Id }, htmlAttributes: new { @class = "btn btn-default" })
                    <button class="btn btn-default" data-toggle="modal" data-target="#deleteImage" type="button">Profielfoto verwijderen</button>
                }

                @Html.ActionLink("Wachtwoord wijzigen", "ChangePassword", "Profiel", new { id = Model.Gebruiker.Id }, htmlAttributes: new { @class = "btn btn-default" })
            </div>
        </div>
        <div class="col-md-10 col-md-offset-2">
            @Image.ShowCurrentImage(Model.Gebruiker.Image, Model.Gebruiker.FirstName)
            <br />
        </div>

        @* FirstName *@
        <div class="form-group">
            @Html.LabelFor(model => model.Gebruiker.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gebruiker.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gebruiker.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        @* LastName *@
        <div class="form-group">
            @Html.LabelFor(model => model.Gebruiker.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gebruiker.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gebruiker.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        @* Email *@
        <div class="form-group">
            @Html.LabelFor(model => model.Gebruiker.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gebruiker.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gebruiker.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        @* Submit *@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" /> | @Html.ActionLink("Annuleren", "Index", "Admin", null, null)
            </div>
        </div>
    </div>
}

@* Modal for deleting image *@
<div class="modal fade" id="deleteImage">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Foto verwijderen</h4>
            </div>
            <div class="modal-body">
                <p>Weet u zeker dat u de foto wilt verwijderen?</p>
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("DeleteImage", null))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Gebruiker.Id)
                    @Html.HiddenFor(model => model.Gebruiker.Email)
                    @Html.HiddenFor(model => model.Gebruiker.FirstName)
                    @Html.HiddenFor(model => model.Gebruiker.LastName)
                    @Html.HiddenFor(model => model.Gebruiker.Level)
                    @Html.HiddenFor(model => model.Gebruiker.Password)
                    @Html.HiddenFor(model => model.Gebruiker.IsBlocked)
                    @Html.HiddenFor(model => model.Gebruiker.LastModifiedAt)
                    @Html.HiddenFor(model => model.Gebruiker.CreatedAt)
                    @Html.HiddenFor(model => model.Gebruiker.MainAccount)
                    @Html.HiddenFor(model => model.Gebruiker.Image)

                    <button type="submit" class="btn btn-default">Ja</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Nee</button>
                }

            </div>
        </div>
    </div>
</div>

CVO/Views/Profiel/EditImage.cshtml
@model CVO.ViewModels.AdminVM
@using CVO.Models
@{
    ViewBag.Title = "Wijzigen";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2 class="text-center">Profielfoto wijzigen</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Gebruiker.Id)
        @Html.HiddenFor(model => model.Gebruiker.Email)
        @Html.HiddenFor(model => model.Gebruiker.FirstName)
        @Html.HiddenFor(model => model.Gebruiker.LastName)
        @Html.HiddenFor(model => model.Gebruiker.Level)
        @Html.HiddenFor(model => model.Gebruiker.Password)
        @Html.HiddenFor(model => model.Gebruiker.IsBlocked)
        @Html.HiddenFor(model => model.Gebruiker.LastModifiedAt)
        @Html.HiddenFor(model => model.Gebruiker.CreatedAt)
        @Html.HiddenFor(model => model.Gebruiker.MainAccount)

        <h2>Huidige foto</h2>
        @Image.ShowCurrentImage(Model.Gebruiker.Image, Model.Gebruiker.FirstName)
        <br />

        @* Image *@
        <h2>Nieuwe profielfoto uploaden</h2>
        @Html.EditorFor(model => model.Gebruiker.Image, new { htmlAttributes = new { @class = "form-control btn btn-info", @Type = "file" } })
        <br />

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Opslaan" class="btn btn-default" /> |
                @Html.ActionLink("Annuleren", "Edit", new { id = Model.Gebruiker.Id })
            </div>
        </div>
    </div>
}